# Generated by Django 6.1.1 on 2026-09-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("opis_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("retail_price", models.FloatField()),
            ],
            options={
                "db_table": "stations",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("city_key", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "us_cities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city_key", "state"), name="unique_city_key_state"
                    )
                ],
            },
        ),
    ]
